language: android
android:
  components:
    - tools
    - platform-tools
    - build-tools-21.1.2
    - android-23
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository